/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { AppStatusResponseVersions } from './appStatusResponseVersions';

export interface AppStatusResponse {
  /** The name of the worker. */
  readonly name?: string;
  /** Timestamp of the last time the worker talked to the service. */
  readonly last_heartbeat?: string;
  /** Versions of the components installed. */
  readonly versions?: AppStatusResponseVersions;
}
