/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for the database connection information
 */
export interface DatabaseConnectionResponse {
  /** Info about whether the app can connect to the database */
  connected: boolean;
}
