/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for information about the Redis connection
 */
export interface RedisConnectionResponse {
  /** Info about whether the app can connect to Redis */
  connected: boolean;
}
