/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export type StatusReadParams = {
/**
 * A list of fields to include in the response.
 */
fields?: string[];
/**
 * A list of fields to exclude from the response.
 */
exclude_fields?: string[];
};
