/**
 * Generated by orval
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { AppStatusResponse } from './app-status-response.ts';
import type { ContentSettingsResponse } from './content-settings-response.ts';
import type { DatabaseConnectionResponse } from './database-connection-response.ts';
import type { RedisConnectionResponse } from './redis-connection-response.ts';
import type { StorageResponse } from './storage-response.ts';
import type { VersionResponse } from './version-response.ts';

/**
 * Serializer for the status information of the app
 */
export interface StatusResponse {
  /** Version information of Pulp components */
  versions: VersionResponse[];
  /** List of online workers known to the application. An online worker is actively heartbeating and can respond to new work. */
  online_workers: AppStatusResponse[];
  /** List of online api apps known to the application. An online api app is actively heartbeating and can serve the rest api to clients. */
  online_api_apps: AppStatusResponse[];
  /** List of online content apps known to the application. An online content app is actively heartbeating and can serve data to clients. */
  online_content_apps: AppStatusResponse[];
  /** Database connection information */
  database_connection: DatabaseConnectionResponse;
  /** Redis connection information */
  redis_connection?: RedisConnectionResponse;
  /** Storage information */
  storage?: StorageResponse;
  /** Content-app settings */
  content_settings: ContentSettingsResponse;
  /** Is Domains enabled */
  domain_enabled: boolean;
}
