/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for information about the storage system
 */
export interface StorageResponse {
  /**
     * Total number of bytes
     * @minimum 0
     * @nullable
     */
  total: number | null;
  /**
     * Number of bytes in use
     * @minimum 0
     * @nullable
     */
  used: number | null;
  /**
     * Number of free bytes
     * @minimum 0
     * @nullable
     */
  free: number | null;
}
