/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for the version information of Pulp components
 */
export interface VersionResponse {
  /** Name of a versioned component of Pulp */
  component: string;
  /** Version of the component (e.g. 3.0.0) */
  version: string;
  /** Python package name providing the component */
  package: string;
  /** Python module name of the component */
  module: string;
  /** Domain feature compatibility of component */
  domain_compatible: boolean;
}
