import { defineConfig } from 'orval';

const targetUrl = 'http://localhost:8080/pulp/api/v3/docs/api.json?pk_path=1';

export default defineConfig({
  core: {
    input: {
      target: targetUrl,
      filters: {
        mode: 'include',
        tags: ['Status'],
      },
    },
    output: {
      client: 'fetch',
      namingConvention: 'kebab-case',
      mode: 'tags',
      target: './src/core/core.ts',
      schemas: { path: './src/core/models', splitByTags: true },
      indexFiles: false,
      clean: true,
      override: {
        mutator: {
          path: './src/mutator/pulp-fetch.ts',
          name: 'pulpFetch',
        },
        fetch: {
          includeHttpResponseReturnType: false,
        },
        header: (info) => [
          'Generated by orval',
          'Do not edit manually.',
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: [
        'npm run update-versions',
        'eslint --fix',
        'prettier --write',
      ],
    },
  },
});
