/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type {
  StatusReadParams
} from '../models/status/statusReadParams';

import type {
  StatusResponse
} from '../models/status/statusResponse';

import { pulpFetch } from '../../mutator/pulp-fetch';

export const getStatusReadUrl = (params?: StatusReadParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["fields","exclude_fields"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }


  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pulp/api/v3/status/?${stringifiedParams}` : `/pulp/api/v3/status/`
}

/**
 * Returns status and app information about Pulp.
 *
 * Information includes:
 *  * version of pulpcore and loaded pulp plugins
 *  * known workers
 *  * known content apps
 *  * database connection status
 *  * redis connection status
 *  * disk usage information
 * @summary Inspect status of Pulp
 */
export const statusRead = async (params?: StatusReadParams, options?: Parameters<typeof pulpFetch>[1]): Promise<StatusResponse> => {

  return pulpFetch<StatusResponse>(getStatusReadUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


