name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '4 4 * * 4'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 384
          days-before-pr-stale: 192
          days-before-close: 32
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned'
          exempt-pr-labels: 'pinned'
          delete-branch: true
